import sys

from PyQt6.QtWidgets import QWidget, QGridLayout, QLabel, QLineEdit, QApplication, QPushButton

from database_tables.msfo_table import Msfo_table


class Enter_Company_Msfo(QWidget):
    def __init__(self):
        super().__init__()
        ticker_label = QLabel('Тикер')
        year_label = QLabel('Год')
        current_assets_label = QLabel('Текущие активы')
        non_current_assets_label = QLabel('Постоянные активы')
        assets_label = QLabel('Активы')
        equity_label = QLabel('Собственный капитал')
        current_liabilities_label = QLabel('Текущие обязательства')
        non_current_liabilities_label = QLabel('Долгосрочные обязательства')
        liabilities_label = QLabel('Обязательства')
        net_debt_label = QLabel('Чистый долг')
        interest_label = QLabel('Процентные платежи')
        sales_label = QLabel('Выручка')
        operating_income_label = QLabel('Операционная прибыль')
        net_income_label = QLabel('Чистая прибыль')
        ebitda_label = QLabel('EBITDA')
        fcf_label = QLabel('FCF')
        dividend_label = QLabel('Дивиденды')

        self.__ticker_line_edit = QLineEdit()
        self.__year_line_edit = QLineEdit()
        self.__current_assets_line_edit = QLineEdit()
        self.__non_current_assets_line_edit = QLineEdit()
        self.__assets_line_edit = QLineEdit()
        self.__equity_line_edit = QLineEdit()
        self.__current_liabilities_line_edit = QLineEdit()
        self.__non_current_liabilities_line_edit = QLineEdit()
        self.__liabilities_line_edit = QLineEdit()
        self.__net_debt_line_edit = QLineEdit()
        self.__interest_line_edit = QLineEdit()
        self.__sales_line_edit = QLineEdit()
        self.__operating_income_line_edit = QLineEdit()
        self.__net_income_line_edit = QLineEdit()
        self.__ebitda_line_edit = QLineEdit()
        self.__fcf_line_edit = QLineEdit()
        self.__dividend_line_edit = QLineEdit()

        self.__ticker_line_edit.setInputMask('>AAAAA')
        self.__year_line_edit.setInputMask('9999')
        self.__current_assets_line_edit.setInputMask('99999999999999')
        self.__non_current_assets_line_edit.setInputMask('99999999999999')
        self.__assets_line_edit.setInputMask('99999999999999')
        self.__equity_line_edit.setInputMask('#9999999999999')
        self.__current_liabilities_line_edit.setInputMask('99999999999999')
        self.__non_current_liabilities_line_edit.setInputMask('99999999999999')
        self.__liabilities_line_edit.setInputMask('99999999999999')
        self.__net_debt_line_edit.setInputMask('#9999999999999')
        self.__interest_line_edit.setInputMask('#9999999999999')
        self.__sales_line_edit.setInputMask('99999999999999')
        self.__operating_income_line_edit.setInputMask('#9999999999999')
        self.__net_income_line_edit.setInputMask('#9999999999999')
        self.__ebitda_line_edit.setInputMask('99999999999999')
        self.__fcf_line_edit.setInputMask('#9999999999999')
        self.__dividend_line_edit.setInputMask('99999999999999')

        ok_button = QPushButton('Сохранить')
        cancel_button = QPushButton('Отмена')
        # ok_button.setSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        # cancel_button.setSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        ok_button.clicked.connect(self.ok_button_clicked)
        cancel_button.clicked.connect(self.cancel_button_clicked)

        layout = QGridLayout()
        layout.setSpacing(10)
        layout.addWidget(ticker_label, 0, 0)
        layout.addWidget(self.__ticker_line_edit, 0, 1)
        layout.addWidget(year_label, 1, 0)
        layout.addWidget(self.__year_line_edit, 1, 1)

        layout.addWidget(current_assets_label, 2, 0)
        layout.addWidget(self.__current_assets_line_edit, 2, 1)
        layout.addWidget(non_current_assets_label, 3, 0)
        layout.addWidget(self.__non_current_assets_line_edit, 3, 1)
        layout.addWidget(assets_label, 4, 0)
        layout.addWidget(self.__assets_line_edit, 4, 1)
        layout.addWidget(equity_label, 5, 0)
        layout.addWidget(self.__equity_line_edit, 5, 1)
        layout.addWidget(current_liabilities_label, 6, 0)
        layout.addWidget(self.__current_liabilities_line_edit, 6, 1)
        layout.addWidget(non_current_liabilities_label, 7, 0)
        layout.addWidget(self.__non_current_liabilities_line_edit, 7, 1)
        layout.addWidget(liabilities_label, 8, 0)
        layout.addWidget(self.__liabilities_line_edit, 8, 1)

        layout.addWidget(net_debt_label, 9, 0)
        layout.addWidget(self.__net_debt_line_edit, 9, 1)
        layout.addWidget(interest_label, 10, 0)
        layout.addWidget(self.__interest_line_edit, 10, 1)

        layout.addWidget(sales_label, 11, 0)
        layout.addWidget(self.__sales_line_edit, 11, 1)
        layout.addWidget(operating_income_label, 12, 0)
        layout.addWidget(self.__operating_income_line_edit, 12, 1)
        layout.addWidget(net_income_label, 13, 0)
        layout.addWidget(self.__net_income_line_edit, 13, 1)

        layout.addWidget(ebitda_label, 14, 0)
        layout.addWidget(self.__ebitda_line_edit, 14, 1)
        layout.addWidget(fcf_label, 15, 0)
        layout.addWidget(self.__fcf_line_edit, 15, 1)
        layout.addWidget(dividend_label, 16, 0)
        layout.addWidget(self.__dividend_line_edit, 16, 1)

        layout.addWidget(ok_button, 17, 0)
        layout.addWidget(cancel_button, 17, 1)

        self.setLayout(layout)
        self.show()

    def ok_button_clicked(self):
        table = Msfo_table(self.__ticker_line_edit.text())
        year = self.__year_line_edit.text()
        table.set_year(year)
        table.set_current_assets(self.__current_assets_line_edit.text(), year)
        table.set_non_current_assets(self.__non_current_assets_line_edit.text(), year)
        table.set_assets(self.__assets_line_edit.text(), year)
        table.set_equity(self.__equity_line_edit.text(), year)
        table.set_current_liabilities(self.__current_liabilities_line_edit.text(), year)
        table.set_non_current_liabilities(self.__non_current_liabilities_line_edit.text(), year)
        table.set_liabilities(self.__liabilities_line_edit.text(), year)
        table.set_interest(self.__interest_line_edit.text(), year)
        table.set_net_debt(self.__net_debt_line_edit.text(), year)
        table.set_sales(self.__sales_line_edit.text(), year)
        table.set_operating_income(self.__operating_income_line_edit.text(), year)
        table.set_net_income(self.__net_income_line_edit.text(), year)
        table.set_ebitda(self.__ebitda_line_edit.text(), year)
        table.set_fcf(self.__fcf_line_edit.text(), year)
        table.set_dividend(self.__dividend_line_edit.text(), year)

    def cancel_button_clicked(self):
        self.close()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    enter_company_msfo = Enter_Company_Msfo()
    sys.exit(app.exec())
