import sys

from PyQt6.QtWidgets import QWidget, QGridLayout, QLabel, QLineEdit, QApplication


class Enter_Company_Msfo(QWidget):
    def __init__(self):
        super().__init__()
        # self.__table = Msfo_table(ticker)

        ticker_label = QLabel('Тикер')
        year_label = QLabel('Год')
        current_assets_label = QLabel('Текущие активы')
        non_current_assets_label = QLabel('Постоянные активы')
        assets_label = QLabel('Активы')
        equity_label = QLabel('Собственный капитал')
        current_liabilities_label = QLabel('Текущие обязательства')
        non_current_liabilities_label = QLabel('Долгосрочные обязательства')
        liabilities_label = QLabel('Обязательства')
        net_debt_label = QLabel('Чистый долг')
        interest_label = QLabel('Процентные платежи')
        sales_label = QLabel('Выручка')
        operating_income_label = QLabel('Операционная прибыль')
        net_income_label = QLabel('Чистая прибыль')
        ebitda_label = QLabel('EBITDA')
        fcf_label = QLabel('FCF')
        dividend_label = QLabel('Дивиденды')

        ticker_line_edit = QLineEdit()
        year_line_edit = QLineEdit()
        current_assets_line_edit = QLineEdit()
        non_current_assets_line_edit = QLineEdit()
        assets_line_edit = QLineEdit()
        equity_line_edit = QLineEdit()
        current_liabilities_line_edit = QLineEdit()
        non_current_liabilities_line_edit = QLineEdit()
        liabilities_line_edit = QLineEdit()
        net_debt_line_edit = QLineEdit()
        interest_line_edit = QLineEdit()
        sales_line_edit = QLineEdit()
        operating_income_line_edit = QLineEdit()
        net_income_line_edit = QLineEdit()
        ebitda_line_edit = QLineEdit()
        fcf_line_edit = QLineEdit()
        dividend_line_edit = QLineEdit()

        ticker_line_edit.setInputMask('>AAAAA')
        year_line_edit.setInputMask('9999')
        current_assets_line_edit.setInputMask('99999999999999')
        non_current_assets_line_edit.setInputMask('99999999999999')
        assets_line_edit.setInputMask('99999999999999')
        equity_line_edit.setInputMask('#9999999999999')
        current_liabilities_line_edit.setInputMask('99999999999999')
        non_current_liabilities_line_edit.setInputMask('99999999999999')
        liabilities_line_edit.setInputMask('99999999999999')
        net_debt_line_edit.setInputMask('#9999999999999')
        interest_line_edit.setInputMask('#9999999999999')
        sales_line_edit.setInputMask('99999999999999')
        operating_income_line_edit.setInputMask('#9999999999999')
        net_income_line_edit.setInputMask('#9999999999999')
        ebitda_line_edit.setInputMask('99999999999999')
        fcf_line_edit.setInputMask('#9999999999999')
        dividend_line_edit.setInputMask('99999999999999')

        layout = QGridLayout()
        layout.setSpacing(10)
        layout.addWidget(ticker_label, 0, 0)
        layout.addWidget(ticker_line_edit, 0, 1)
        layout.addWidget(year_label, 1, 0)
        layout.addWidget(year_line_edit, 1, 1)

        layout.addWidget(current_assets_label, 2, 0)
        layout.addWidget(current_assets_line_edit, 2, 1)
        layout.addWidget(non_current_assets_label, 3, 0)
        layout.addWidget(non_current_assets_line_edit, 3, 1)
        layout.addWidget(assets_label, 4, 0)
        layout.addWidget(assets_line_edit, 4, 1)
        layout.addWidget(equity_label, 5, 0)
        layout.addWidget(equity_line_edit, 5, 1)
        layout.addWidget(current_liabilities_label, 6, 0)
        layout.addWidget(current_liabilities_line_edit, 6, 1)
        layout.addWidget(non_current_liabilities_label, 7, 0)
        layout.addWidget(non_current_liabilities_line_edit, 7, 1)
        layout.addWidget(liabilities_label, 8, 0)
        layout.addWidget(liabilities_line_edit, 8, 1)

        layout.addWidget(net_debt_label, 9, 0)
        layout.addWidget(net_debt_line_edit, 9, 1)
        layout.addWidget(interest_label, 10, 0)
        layout.addWidget(interest_line_edit, 10, 1)

        layout.addWidget(sales_label, 11, 0)
        layout.addWidget(sales_line_edit, 11, 1)
        layout.addWidget(operating_income_label, 12, 0)
        layout.addWidget(operating_income_line_edit, 12, 1)
        layout.addWidget(net_income_label, 13, 0)
        layout.addWidget(net_income_line_edit, 13, 1)

        layout.addWidget(ebitda_label, 14, 0)
        layout.addWidget(ebitda_line_edit, 14, 1)
        layout.addWidget(fcf_label, 15, 0)
        layout.addWidget(fcf_line_edit, 15, 1)
        layout.addWidget(dividend_label, 16, 0)
        layout.addWidget(dividend_line_edit, 16, 1)

        self.setLayout(layout)
        self.show()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    enter_company_msfo = Enter_Company_Msfo()
    sys.exit(app.exec())
